



POST http://localhost:3030/api/productos
Content-Type: application/json

{
    "nombre":"Adhesivo Dap Dynagrip Blanco 5onz",
    "precio":150,
    "stock":10,
    "imagenes":[
        {"imagenUrl":"09350497.webp"}
    ]
}
