GET http://localhost:3030/api/auth/me
Authentication: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY29ycmVvIjoiaG9sYUBob2xhLmNvbSIsImlhdCI6MTY0NjMyMjMxMSwiZXhwIjoxNjQ2MzIyMzQxfQ.aTu0WmVTptdbKtC0v_srn_S17WqlMKrLt3MX6n1cgHU

####
POST http://localhost:3030/api/auth/login
Content-Type: application/json

{
   "correo":"hola@hola.com",
    "clave":"hola"
}
###
POST http://localhost:3030/api/auth/registro
Content-Type: application/json

{
    "nombre":"hola",
    "correo":"hola@hola.com",
    "clave":"hola"
}


###
DELETE http://localhost:3030/api/auth/logout
Authentication: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY29ycmVvIjoiaG9sYUBob2xhLmNvbSIsImlhdCI6MTY0NjMyMTI5OSwiZXhwIjoxNjQ2MzIxMzI5fQ.qPIQACCmA245NWWQSrZU-NVtwMokgM_vps-fUEtilKI


####
GET http://localhost:3030/api/auth/refresh
Content-Type: application/json
 
{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY29ycmVvIjoiaG9sYUBob2xhLmNvbSIsImlhdCI6MTY0NjMyMTg0OH0.0v7GwYJe1-JZpU1KSD4oA6y8teSgjFPLr19Hzh1t974"
}