GET http://localhost:3030/api/auth/me
Authentication: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY29ycmVvIjoiaG9sYUBob2xhLmNvbSIsImlhdCI6MTY0NjMzODk3MywiZXhwIjoxNjQ2MzM5MDkzfQ.6oMBAQG5iYVfG8XGTezHMsIpz6XSYmOTPlEqifiHb6U

####
POST http://localhost:3030/api/auth/login
Content-Type: application/json

{
   "correo":"hola@hola.com",
    "clave":"hola"
}
###
POST http://localhost:3030/api/auth/registro
Content-Type: application/json

{
    "nombre":"hola",
    "correo":"hola@hola.com",
    "clave":"hola"
}


###
DELETE http://localhost:3030/api/auth/logout
Authentication: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY29ycmVvIjoiaG9sYUBob2xhLmNvbSIsImlhdCI6MTY0NjMyMTI5OSwiZXhwIjoxNjQ2MzIxMzI5fQ.qPIQACCmA245NWWQSrZU-NVtwMokgM_vps-fUEtilKI


####
GET http://localhost:3030/api/auth/refresh
Content-Type: application/json
 
{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY29ycmVvIjoiaG9sYUBob2xhLmNvbSIsImlhdCI6MTY0NjMzODk5OH0.ked-_x7O-KqYVXbjvs4yFq-SLFfZUlUUpUCIRgDAcJI"
}

####
DELETE http://localhost:3030/api/auth/logout
Authentication: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY29ycmVvIjoiaG9sYUBob2xhLmNvbSIsImlhdCI6MTY0NjMzODk3MywiZXhwIjoxNjQ2MzM5MDkzfQ.6oMBAQG5iYVfG8XGTezHMsIpz6XSYmOTPlEqifiHb6U